#!/bin/bash

# Rscript 01_pull_gcc_weather.R
python3 02_PEG_RFR0_gcc_predictions.py
python3 03_PEG_RFR_gcc_predictions_with_interpolation.py
python3 04_PEG_RFR2_gcc_predictions_with_weather_variables.py
Rscript 05_submit_rfr.R